Enigmath/Enigmath/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from accounts.views import (login_view, register_view, logout_view)
from main.views import(main_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^news/', include("news.urls", namespace='news')),
    url(r'^profile/', include("accounts.urls", namespace='accounts')),
    url(r'^olympiads/', include("olymps.urls", namespace='olymps')),
    url(r'^problems/', include("problems.urls", namespace='problems')),
    url(r'^', include("main.urls", namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Enigmath/main/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    main_view,
    contacts_view,
    )

app_name = 'Enigmath'
urlpatterns = [
    url(r'^$', main_view, name='home'),
    url(r'^contacts/$', contacts_view, name='contacts'),
]

Enigmath/news/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	news_list,
	news_create,
	news_detail,
	news_update,
	news_delete,
	)

app_name = 'Enigmath'
urlpatterns = [
	url(r'^$', news_list, name='list'),
    url(r'^create/$', news_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', news_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', news_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', news_delete, name='delete'),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

Enigmath/problems/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    problem_thread,
    problem_delete,
 #   expression_delete,
    )

app_name = 'Enigmath_problems'
urlpatterns = [
    url(r'^(?P<id>\d+)/$', problem_thread, name='thread'),
    url(r'^(?P<id>\d+)/delete/$', problem_delete, name='delete'),
#    url(r'^(?P<expression_text>[\w-]+)/delete_expression/$', expression_delete, name='exp_delete'),
]

Enigmath/problems/models.py
from __future__ import unicode_literals

from django.conf import settings

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import pre_save
from django.utils import timezone


from django.utils.text import slugify
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from transliterate import translit, get_available_language_codes

from django.urls import reverse

from django.db import models
from django.contrib.postgres.fields import HStoreField
from django.contrib.postgres.fields import ArrayField

from accounts.models import Profile


# Create your models here.\


class ProblemManager(models.Manager):
    def all(self):
        return super(ProblemManager, self)

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return super(ProblemManager, self).filter(content_type=content_type, object_id= instance.id)

    def filter_by_author(self, author):
        return super(ProblemManager, self).filter(user=author)


class Problem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete = models.PROTECT)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null = True)
    object_id = models.PositiveIntegerField(null = True)
    content_object = GenericForeignKey('content_type', 'object_id')

    content = models.TextField()
    title = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ProblemManager()

    class Meta:
        ordering = ['timestamp']

    def __unicode__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("problems:thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("problems:delete", kwargs={"id": self.id})
    
    def get_profile(self):
        return reverse("accounts:profile", kwargs={"user":self.user})



class CheckProblem(models.Model):
    user = models.PositiveIntegerField(null = True)
    problem_id = models.PositiveIntegerField(null = True)
    actions = ArrayField(ArrayField(models.TextField()), default=[['f', 'f']])
    solved = models.BooleanField(default=False) 


    # def delete():
    #     return reverse("problems:exp_delete")

Enigmath/problems/forms.py
from django import forms

from .models import Problem
from django.forms import CharField


class CreateProblemForm(forms.ModelForm):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(label='', widget=forms.Textarea)
    class Meta:
        model = Problem
        fields = [
            "title",
            "content",
        ]

Enigmath/main/views.py
from django.shortcuts import render, redirect
from accounts.models import Profile





def main_view(request):
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    
    staff = "no"
    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"
    context = {
    	"staff":staff,
	    "user":request.user,
        "profile":profile,
    }
    return render(request, "main.html", context)


def contacts_view(request):
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    
    staff = "no"
    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"
    context = {
        "staff":staff,
        "user":request.user,
        "profile":profile,
    }
    return render(request, "contacts.html", context)

Enigmath/problems/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404

from accounts.models import Profile
from .solve_problem_form import SaveProblemForm

from .expression_form import ExpressionForm
from .models import Problem
from .models import CheckProblem

from olymps.models import Olymp
from lemmas.isequal import isequal


def problem_delete(request, id):
    try:
        obj = Problem.objects.get(id=id)
    except:
        raise Http404

    if obj.user != request.user:
        reponse.status_code = 403
        return HttpResponse("You do not have permission to do this.")

    if request.method == "POST":
        parent_obj_url = obj.content_object.get_absolute_url()

        for checkprblm in CheckProblem.objects.filter(problem_id = obj.id):
            checkprblm.delete()

        obj.delete()
        messages.success(request, "This has been deleted.")
        return HttpResponseRedirect(parent_obj_url)
    
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    staff = "no"

    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"

    context = {
        "staff":staff,
        "profile":profile,
        "object": obj,
    }
    return render(request, "confirm_delete.html", context)

def problem_thread(request, id):
    try:
        obj = Problem.objects.get(id=id)
    except:
        raise Http404

    content_object = obj.content_object 
    content_id = obj.content_object.id

    initial_data = {
            "content_type": obj.content_type,
            "object_id": obj.object_id
    }

    if request.user.id:
        check_problem = CheckProblem.objects.get(problem_id = obj.id, user = request.user.id)
    else:
        messages.warning(request, "You need to authanticate to see problems")
        return HttpResponseRedirect(obj.content_object.get_absolute_url())
    
    action_check = ''
    action_check2 = ''

    
    expression_form = ExpressionForm(request.POST or None)
    
    save_problem_form = SaveProblemForm(request.POST or None)
    if expression_form.is_valid():
        expr_id = expression_form.cleaned_data.get('exp_id') - 1
        if 'delete' in request.POST:
            check_problem.actions.pop(expr_id) 
            check_problem.save()
            return HttpResponseRedirect(obj.get_absolute_url())
        if 'use' in request.POST:
            init_data = {
                'expr2': check_problem.actions[expr_id][0]
            }
            save_problem_form = SaveProblemForm(request.POST or None, initial = init_data)
        
    if save_problem_form.is_valid():
        expr1 = save_problem_form.cleaned_data.get('expr1')
        expr2 = save_problem_form.cleaned_data.get('expr2')
        action_check = isequal(expr1)
        if action_check == '':
            action_check2 = isequal(expr2)

        if 'save' in request.POST:
            if action_check != '':
                check_problem.actions.append([expr1, action_check])
                check_problem.save()
                return HttpResponseRedirect(obj.get_absolute_url())  
            elif action_check2 != '':
                check_problem.actions.append([expr2, action_check2])
                check_problem.save()
                return HttpResponseRedirect(obj.get_absolute_url()) 
    
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    staff = "no"
    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"
    
    

    context = {
        "staff":staff,
        "profile":profile,
        "problem": obj,
        "save_problem_form": save_problem_form,
        "check_problem": check_problem,
        "action_check":action_check,
        "expression_form": expression_form,
    }
    return render(request, "problem.html", context)

Enigmath/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
	<meta charset="utf-8">
	<title>{% block head_title %}Enigmath{% endblock head_title %}</title>


	
	<!-- CSS -->
	<link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet" type="text/css" />
	<link href='{% static "css/style.css" %}' rel="stylesheet" type="text/css" />
	<link rel='stylesheet' href='{% static "css/base.css" %}' />
	<link rel="shortcut icon" href='{% static "images/favicon.ico" %}' type="image/png">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	
	<link href="https://fonts.googleapis.com/css?family=Anton|Francois+One|Kanit|Oswald" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Changa:800|Montserrat:900" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


	<style>
		{% block style %}{% endblock style %}
	</style>
	{% block head_extra %} {% endblock head_extra %}
</head>

<body>
	<header>

			<div class="menu_block">
					<br>
					<div class="logo col-sm-4 col-sm-offset-4 ">
						<a href='{% url "main:home" %}' >E n i g m a t h</a>
					</div><!-- //LOGO -->
						<nav class="navmenu2" >
							<ul>
								{% if request.user.is_authenticated %}		
									<li class='pull-right'><a href='{% url "logout" %}'><i class="fas fa-sign-out-alt"></i>Logout</a></li>
									<li class='pull-right'><a href='{{ profile.get_absolute_url }}'><i class="fas fa-user"></i> {{ user }}</a></li>
								{% else %}
									<li class='pull-right'><a href='{% url "register" %}'><i class="fas fa-user-plus"></i> Sign up</a></li>
									<li class='pull-right'><a href='{% url "login" %}'><i class="fas fa-sign-in-alt"></i> Login</a></li>
								{% endif %}	
							</ul>

						</nav>


				<div class="container ">
					<div>
						<nav class="navmenu" >

							<ul>
								<li class="btn-menu-e"><a href='{% url "olymps:list" %}' >Olympiads</a></li>
								<li class="btn-menu-e"><a href='{% url "news:list" %}' >Ratings</a></li>
								<li class="btn-menu-e "><a href='{% url "news:list" %}' >News</a></li>
								<li class="btn-menu-e"><a href='{% url "main:contacts" %}' >Contacts</a></li>
								<li class="btn-menu-e last "><a href='{% url "main:contacts" %}' >School</a></li>

							</ul>

							
						</nav>
					</div><!-- //MENU -->
				</div><!-- //MENU BLOCK -->
			</div><!-- //CONTAINER -->
		</header><!-- //HEADER -->
	<div id="fb-root"></div>

<script type="text/javascript" src="https://vk.com/js/api/share.js?95" charset="windows-1251"></script>

	<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<br><br><hr>


	{% include "messages_display.html" %}
	<div class='content-container'>
	{% block content %}{% endblock content %}
	</div>

	<!-- FOOTER -->
	<footer>
			
		<!-- CONTAINER -->
		<div class="container">
			
			<!-- ROW -->
			<div class="row" data-animated="fadeInUp">
				
				<div class="col-lg-4 col-md-4 col-sm-6 padbot30">
					<h4><b>Featured</b> posts</h4>
					<div class="recent_posts_small clearfix">
						<div class="post_item_img_small">
							
						</div>
						<div class="post_item_content_small">
							<a class="title" href="blog.html" >As we have developed a unique layout template</a>
							<ul class="post_item_inf_small">
								<li>10 January 2014</li>
							</ul>
						</div>
					</div>
					<div class="recent_posts_small clearfix">
						<div class="post_item_img_small">
							
						</div>
						<div class="post_item_content_small">
							<a class="title" href="blog.html" >How much is to develop a design for the game?</a>
							<ul class="post_item_inf_small">
								<li>14 January 2014</li>
							</ul>
						</div>
					</div>
					<div class="recent_posts_small clearfix">
						<div class="post_item_img_small">
							
						</div>
						<div class="post_item_content_small">
							<a class="title" href="blog.html" >How to pump designer</a>
							<ul class="post_item_inf_small">
								<li>21 December 2013</li>
							</ul>
						</div>
					</div>
				</div>
				
				<div class="col-lg-4 col-md-4 col-sm-6 padbot30 foot_about_block">
					<h4><b>About</b> us</h4>
					<p>We value people over profits, quality over quantity, and keeping it real. As such, we deliver an unmatched working relationship with our clients.</p>
					<p>Our team is intentionally small, eclectic, and skilled; with our in-house expertise, we provide sharp and</p>
					<ul class="social">
						<li><a href="javascript:void(0);" ><i class="fa fa-twitter"></i></a></li>
						<li><a href="javascript:void(0);" ><i class="fa fa-facebook"></i></a></li>
						<li><a href="javascript:void(0);" ><i class="fa fa-google-plus"></i></a></li>
						<li><a href="javascript:void(0);" ><i class="fa fa-pinterest-square"></i></a></li>
						<li><a href="javascript:void(0);" ><i class="map_show fa fa-map-marker"></i></a></li>
					</ul>
				</div>
				
				<div class="respond_clear"></div>
				
				<div class="col-lg-4 col-md-4 padbot30">
					<h4><b>Contacts</b> Us</h4>
					
					<!-- CONTACT FORM -->
					<div class="span9 contact_form">
						<div id="note"></div>
						<div id="fields">
							<form id="contact-form-face" class="clearfix" action="#">
								<input type="text" name="name" value="Name" onFocus="if (this.value == 'Name') this.value = '';" onBlur="if (this.value == '') this.value = 'Name';" />
								<textarea name="message" onFocus="if (this.value == 'Message') this.value = '';" onBlur="if (this.value == '') this.value = 'Message';">Message</textarea>
								<input class="contact_btn" type="submit" value="Send message" />
							</form>
						</div>
					</div><!-- //CONTACT FORM -->
				</div>
			</div><!-- //ROW -->
		</div><!-- //CONTAINER -->
	</footer><!-- //FOOTER -->




	<!-- Latest compiled and minified JavaScript -->

	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

	<script src='{% static "js/jquery.min.js" %}' type="text/javascript"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	
	<script src='{% static "js/myscript.js" %}' type="text/javascript"></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>


	<script type="text/javascript">
		$(document).ready(function(){
		    $(".content-markdown").each(function(){
		            var content = $(this).text()
		            var markedContent = marked(content)
		            $(this).html(markedContent)
		    })
		    $(".post-detail-item img").each(function(){
		            $(this).addClass("img-responsive");
		    })



			var contentInput = $("#id_content");
		    function setContent(value){		   
		        $("#preview-content").html(marked(value))
		        $("#preview-content img").each(function(){
		            $(this).addClass("img-responsive")
		        })
		    }
		    setContent(contentInput.val())
		    contentInput.keyup(function(){
		        var newContent = $(this).val()
		        setContent(newContent)
		    })

		    var titleInput = $("#id_title");
		    
		    function setTitle(value) {
		        $("#preview-title").text(value)
		    }
		    setTitle(titleInput.val())
		    titleInput.keyup(function(){
		        var newContent = $(this).val()
		        setTitle(newContent)
		    })

		    $(".comment-reply-btn").click(function(event){
       			event.preventDefault();
        		$(this).parent().next(".comment-reply").fadeToggle();
    		})
		    $(".comment-children-reply-btn").click(function(event){
       			event.preventDefault();
        		$(this).parent().next(".comment-reply").fadeToggle();
    		})

   


		})
	</script>




</body>
</html>

Enigmath/templates/news_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}




{% block content %}
<div class='col-sm-7 col-sm-offset-1'>
	{% if staff == "yes" %} 
		<h4 style="color: red"> Staff only: <a class="btn btn-info" href='{% url "news:create" %}' >Create Post</a></h3>
	{% endif %}
    <br><br>
    <a class="btn btn-default" href='{% url "news:list" %}'>
			<i class="fas fa-chevron-circle-left"></i> Back to list 
		</a>
	<h1>{{ title }} <small>{{ instance.publish }}</small></h1>
	

		<p>Author: <a href="{{ instance.get_author }}">{{ instance.user.username }}</a> </p>

	{% if staff == "yes" %} 
        <a href='{{ instance.get_delete_url }}'>Delete</a> |
        <a href='{{ instance.get_update_url }}'>Edit</a>
    {% endif %}

	<div class='row'>
		<div class='col-sm-12'>
			{{ instance.get_markdown }}
		<hr/>
		{% if instance.image %}
	    	<img src='{{ instance.image.url }}' />
		{% endif %}

		<br/>

		</div>
	</div>
	<p><br></p>
		
    <hr/>
    <br/>

    <div>
        <p class='lead'>
			{{ comments.count }} Comment{% if comments.count > 1 or comments.count == 0 %}s{% endif %}
        </p>
        {% if is_auth == False %}
	    	Please, <a href='{% url "login" %}'>login</a> to comment
	    {% endif %}
        <hr/>

        {% for comment in comments_parents %}
			<blockquote>
				
				
					{% if comment.author.image %}
						<a href="{{ comment.get_profile }}">
							<img class="user_img_comments" src="{{ comment.author.image.url }}">
						</a>
					{% endif %}
				
				
				<a href="{{ comment.get_profile }}">
					{{ comment.user }}
				</a>
 		        <p>{{ comment.content }}</p>
		        <div class="small-details">
			        {{ comment.timestamp|timesince }} ago 
			        {% if is_auth == True %}
				        <a class='comment-reply-btn' href='#'>
				        	| Reply
				        </a>
				    {% endif %}
			        {% if request.user == comment.user or staff == "yes" %} | <a href='{{ comment.get_delete_url }}'>Delete</a>
			        {% endif %}
		        </div>
		        {% if is_auth == True %}
			        <div class='comment-reply'>  
			        	<form method="POST" action="." enctype="multipart/form-data"> {% csrf_token %}
			                {{ comment_form }}
			                <br><br>
			                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
			                <input type='submit' value='Reply' class='btn btn-info'>
			            </form>
			        </div>
			    {% endif %}

		        {% for child_comment in comment.children %}
		        		<br>
		                <blockquote>
		                	
		                	{% if child_comment.author.image %}
								<a href="{{ child_comment.get_profile }}">
									<img class="user_img_comments" src="{{ child_comment.author.image.url }}">
								</a>
							{% endif %}
							
			                <a href="{{ child_comment.get_profile }}">{{ child_comment.user }}</a>
			                <p>{{ child_comment.content }}</p>
			                <div class="small-details">{{ child_comment.timestamp|timesince }} ago
				                {% if is_auth == True %}
					                <a class='comment-children-reply-btn' href='#'>
					        			| Reply
					        		</a>
					        	{% endif %}
			                	{% if request.user == child_comment.user  or staff == "yes"%} 
                    		      | <a href='{{ child_comment.get_delete_url }}'>Delete</a>
                        		{% endif %}
			                </div>
			                {% if is_auth == True %}
				                <div class='comment-reply'>  
						        	<form method="POST" action="."> {% csrf_token %}
						                {{ comment_form }}
						                <br><br>
						                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
						                <input type='submit' value='Reply' class='btn btn-info'>
						            </form>
			        			</div>	
			        		{% endif %}	                
		                </blockquote>
		        {% endfor %}


	        </blockquote>

	         <hr/>

        {% endfor %}
        {% if is_auth == True %}
	        <form class="comment_form" method="POST" action='' enctype='multipart/form-data'> {% csrf_token %}
	            {{ comment_form }}
	            <br><br>
	            <input type='submit' class='btn btn-info' value='Post comment' >
	        </form>
	    {% endif %}

        <br><br><br><br>
    </div>

</div>






{% endblock content %}

Enigmath/templates/news_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-7 col-sm-offset-1'>
    <h3 class="main-h1">{{ title }}</h1>

    {% if staff == "yes" %} 
        <h4 style="color: red"> Staff only: <a class="btn btn-info" href='{% url "news:create" %}' >Create Post</a></h3>
    {% endif %}
    <br><br>

                                
    {% for obj in object_list %}
    <div class="row">
      <div class="col-sm-12">
        <div class="thumbnail">
          <div class="caption">
            
            {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
            
            <h3>
                <a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> 
                <small>{{ obj.publish }}</small>
            </h3>
            <p>Author: <a href="{{ obj.get_author }}">{{ obj.user.username }}</a> </p>

            {% if staff == "yes" %} 
                <a href='{{ obj.get_delete_url }}'>Delete</a> |
                <a href='{{ obj.get_update_url }}'>Edit</a>
            {% endif %}
            
            <p>{{ obj.get_markdown|truncatechars_html:20}}</p>

            {% if obj.image %}
                <img src='{{ obj.image.url }}'/>
            {% endif %}
            <p><br></p>

            <div class='' >
                <p class="likes_count">{{ obj.likes }} </p>
                <a href=""><i class="fas fa-caret-up like_btn"></i></a> 
                <a href=""><i class="fas fa-caret-down like_btn"></i></a> 
            </div>
            <a class="btn btn-info" href="{{ obj.get_absolute_url }}">View Post</a>
            <a class="btn btn-default" href="{{ obj.get_absolute_url }}">{% if obj.comments.count == 0 %}Make first comment{% endif %} {% if obj.comments.count > 0 %}{{ obj.comments.count }} comment{% if obj.comments.count > 1 %}s{% endif %}{% endif %}</a>
          
          </div>
        </div>
      </div>
    <hr/> 
    </div>
    {% endfor %}


    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>




</div>
<p><br><br><br></p>
<div class='col-sm-3 col-sm-onset-8'>
    <form method='GET' action=''>
        <div class="input-group">
            <input type='text' name='q' placeholder='Search news' value='{{ request.GET.q }}'/>
            <span class="input-group-btn">
                <button class="btn btn-active" type="submit"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </form>

</div>

{% endblock content %}

Enigmath/templates/olymp_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}




{% block content %}
<div class='col-sm-10 col-sm-offset-1'>
    {% if staff == "yes" %} 
	   <h4 style="color: red"> Staff only: <a class="btn btn-info" href='{% url "olymps:create" %}' >Create Olympiad</a></h3>
    {% endif %}   
	<div class="col-sm-offset-6">
        <h2>{{ instance.title }} </h2>
        {% if staff == "yes" %} 
	        <a href='{{ instance.get_update_url }}'>Edit</a> |
	        <a href='{{ instance.get_delete_url }}'>Delete</a>
        {% endif %}
    </div>

    <br/>

    <div>

        <hr/>        
        {% for element_of_user in array_of_user %}  
			<a href='{{ element_of_user.0.get_absolute_url }}'><h4>{{ element_of_user.0.title }}</h4></a>
            {% if is_auth == True %}
                {% if element_of_user.1.0.solved == False %}
                    <h4>Not solved</h4>
                {% else %}
                    <h4>Solved</h4>
                {% endif %}
            {% endif %}


	        

            {% if staff == "yes" %}<a href='{{ element_of_user.0.get_delete_url }}'>Delete</a>{% endif %}
	        <hr/>
        {% endfor %}


		<!--<a class="btn btn-info" href="">Create problem</a>-->
        <br><br>
    </div>
    {% if staff == "yes" %} 
        <h4 style="color: red"> Staff only</h4><h4>Create new Problem:</h4>
        <br>        
        <form class="comment_form" method="POST" action='' enctype='multipart/form-data'> {% csrf_token %}
            {{ create_problem_form|crispy }}
            <br><br>
            <input type='submit' class='btn btn-info' value='Create problem' >
        </form>
    {% endif %}
        <br><br><br><br><br><br><br><br><br><br><br><br>

</div>






{% endblock content %}